[project]
name = "fastapi-movie-catalog"
version = "0.1.0"
description = "A learning project from the @mahenzon course"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
]
